### ISSUE TITLE
Relative URL doesn't work with appHandler: "Invalid URL" error

### ISSUE THREAD

**Issue by rorysaur** [Xunnamius/next-test-api-route-handler#1000]
<details open><summary><strong>The problem</strong></summary>

It seems [this commit about normalization of URLs](https://github.com/Xunnamius/next-test-api-route-handler/commit/8400a194cf3a824209a8175f48bdd4f0e4c43f8c) may have broken the ability to use a relative-style `url` param with the app handler because calling `new URL(url)` on a path like `"/my-url"` throws `Invalid URL` error (as one would expect it to, since `new URL()` doesn't accept relative URLs).

```
    TypeError: Invalid URL

      at normalizeUrlForceTrailingSlashIfPathnameEmpty (node_modules/.pnpm/next-test-api-route-handler@4.
0.3_next@14.1.0/node_modules/next-test-api-route-handler/dist/src/index.js:337:16)
```

I was able to get around this easily by providing a dummy beginning of the url as the tests do (e.g. `"ntarh://api/books"` instead of just `"/api/books"`), but it doesn't match what the docs say, so it required some digging to figure this out.

I noticed the tests include a case with `url: '/my-url'` and `pagesHandler`, but not a case for the same url with `appHandler`. I believe that's the case that's broken.

</details>

<details><summary><strong>Reproduction steps</strong></summary>

1. Run a basic example like:
```
it("works", async () => {
  await testApiHandler({
    appHandler,
    url: "/my-url",
    async test({ fetch }) {
      const res = await fetch({
        method: "GET",
      })

      const json = await res.json()

      expect(json).toStrictEqual([])
    },
  })
})
```

</details>

**Comment by rorysaur** [comment]
Wow, lucky #1000! 🌟

**Comment by Xunnamius** [comment]
Hmm. The Pages Router doesn't use the `URL` class and so accepts those relative style urls, but the App Router seems to exclusively use the `URL` class, which explains that discrepancy.  The `URL` class requires an absolute url, which is why that `ntarh://` version works (it could also be `https://`).

I'll go over the documentation to make sure it's clearer. I haven't used the App Router in production yet, but it doesn't seem like the App Router itself supports relative urls (i.e. all urls seem to be some instance of the `URL` class and/or `NextUrl`). If this assumption isn't accurate, I'll have to address that as well :)
