### ISSUE TITLE
Module not found: Can't resolve 'next/dist/next-server/server/api-utils.js' in '.../node_modules/next-test-api-route-handler/dist/esm'

### ISSUE THREAD

**Issue by hems** [Xunnamius/next-test-api-route-handler#378]
<details open><summary><strong>The problem</strong></summary>

Just updated next.js to version 12 and now the project build is failing.

Curiously the tests are still passing, but "next build" fails with the following error:

````
$ next build --debug
 ******* next.config.js building:
            NODE_ENV: production
                 ENV: localhost
info  - Checking validity of types...
warn  - The Next.js plugin was not detected in your ESLint configuration. See https://nextjs.org/docs/basic-features/eslint#migrating-existing-config
info  - Creating an optimized production build...
warn  - Disabled SWC as replacement for Babel because of custom Babel configuration ".babelrc" https://nextjs.org/docs/messages/swc-disabled
info  - Using external babel configuration from /home/runner/my-project/.babelrc
Failed to compile.

./node_modules/next-test-api-route-handler/dist/esm/index.mjs
Module not found: Can't resolve 'next/dist/next-server/server/api-utils.js' in '/home/runner/my-project/node_modules/next-test-api-route-handler/dist/esm'

Import trace for requested module:
./src/pages/api/my-endpoint.test.ts

./node_modules/next-test-api-route-handler/dist/esm/index.mjs
Module not found: Can't resolve 'next-server/dist/server/api-utils.js' in '/home/runner/my-project/node_modules/next-test-api-route-handler/dist/esm'

Import trace for requested module:
./src/pages/api/my-endpoint.test.ts
````

</details>

<details><summary><strong>Reproduction steps</strong></summary>

I guess you just need to create a test and import `next-test-api-route-handler`, like this:

`import { testApiHandler } from 'next-test-api-route-handler'`

and then run `next build`.

</details>

<details><summary><strong>Additional context</strong></summary>

- OS: OSX
- Node version: 12.22.7

</details>

**Comment by hems** [comment]
> @hems By chance are you using npm 6.x? `UNMET PEER DEPENDENCY next@12.0.1` is super weird.

yes, i'm using `6.14.15`... i'm a supposed to be using a newer versiono? 😓

**Comment by Xunnamius** [comment]
[NPM doesn't install peer dependencies by default before version 7](https://github.blog/2021-02-02-npm-7-is-now-generally-available/#peer-dependencies), along with other little changes to how `npm@>=7` organizes installs and records them to `package-lock.json`. It'd be a little strange if you didn't have Next.js itself installed already (I don't see it in the output of your `npm list...` output above), but if you don't, you should ensure it's installed such that no "unmet peer dependency" errors occur.

Also, what output do you get when running `npm list --depth=1 | grep next` (or its Windows equivalent) at your project root?

I'd expect to see something like this:
```
npm list --depth=1 | grep next
...
├─┬ next-test-api-route-handler@2.2.1
│ ├── next@12.0.1 deduped
...
├─┬ next@12.0.1
│ ├── @next/env@12.0.1
│ ├── @next/polyfill-module@12.0.1
│ ├── @next/react-dev-overlay@12.0.1
│ ├── @next/react-refresh-utils@12.0.1
...
```

**Comment by Xunnamius** [comment]
Hmm, regardless, it looks like there is [something special](https://github.com/Xunnamius/next-test-api-route-handler/runs/4075906331?check_suite_focus=true) about node 12.x and 14.x. Getting closer...

**Comment by Xunnamius** [comment]
@hems Seems the problem was three-fold:

1. I noticed in your report you're using `node@12`. Turns out there were various little incompatibilities with `node@14` and `node@12`. Originally I thought to run integration tests over all Next.js versions but not across all supported _Node.js_ versions too 🤦🏿‍♂️.

2. Webpack would compile out the import fallback code under certain circumstances.

3. `node@<15` ships with `npm@<7`, which infamously [does not support automatic peer dependency installation](https://github.blog/2021-02-02-npm-7-is-now-generally-available/#peer-dependencies). For those using an old version of Node.js/NPM, you have to **manually install `next`** (whatever version) _**and its peer dependencies**_, otherwise NTARH will fail to import `next` even if it is available. I've updated the README.md to reflect this.

Installing `next-test-api-route-handler@>=2.3.0` should resolve this issue. If it doesn't, feel free to reopen. Thanks again for this bug report, it resulted in a major fix 👍🏿
