### ISSUE TITLE
ReferenceError: Request is not defined

### ISSUE THREAD

**Issue by kingstarfly** [Xunnamius/next-test-api-route-handler#999]
<details open><summary><strong>The problem</strong></summary>

I'm encountering a `ReferenceError: Request is not defined` when attempting to test an API route using next-test-api-route-handler. The test is designed to verify that a GET request to `/api/test` should return `{hello: 'world'}`. However, the test fails with the mentioned error.

Here's the code snippet where the error occurs:

```javascript
import { testApiHandler } from "next-test-api-route-handler";

describe("GET /api/test", () => {
  it("Returns {hello: 'world'}", async () => {
    await testApiHandler({
      appHandler: {
        GET: async () => {
          return Response.json({ hello: "world" }, { status: 200 });
        },
      },

      async test({ fetch }) {
        const res = await fetch();
        expect(res.status).toBe(200);
        const json = await res.json();
        expect(json).toStrictEqual({ hello: "world" });
      },
    });
  });
});
```

</details>

<details><summary><strong>Reproduction steps</strong></summary>

</details>

<details><summary><strong>Additional context</strong></summary>

- OS: Mac 14.2.1
- Node version: 20.10.0
- Babel: yes, version 7.18
- TypeScript: yes, version 5.2.2
- Next.js: 13.5.4
- Jest: 29.6.1

Error message in terminal:

```vbnet
ReferenceError: Request is not defined

  37 | describe("GET /api/test", () => {
  38 |   it("Returns {hello: 'world'}", async () => {
> 39 |     await testApiHandler({
     |                         ^
  40 |       appHandler: {
  41 |         GET: async () => {
  42 |           return Response.json({ hello: "world" }, { status: 200 });

  at Object.Request (node_modules/next/src/server/web/spec-extension/request.ts:10:34)
  at Object.<anonymous> (node_modules/next/server.js:2:16)
  at createAppRouterServer (node_modules/next-test-api-route-handler/dist/src/index.js:161:25)
  at testApiHandler (node_modules/next-test-api-route-handler/dist/src/index.js:110:57)
  at Object.<anonymous> (tests/route.test.ts:39:25)

```
</details>

**Comment by Xunnamius** [comment]
Woah, that's interesting. Are you sure you're running this on Node 20 and not Node <16.15? Global [`Request`](https://nodejs.org/api/globals.html#request) was introduced with Node 18.

**Comment by Xunnamius** [comment]
Ah, I just noticed you're using a Next.js version below 14 along with the App Router. As noted in the [Legacy Runtime Support](https://github.com/Xunnamius/next-test-api-route-handler?tab=readme-ov-file#legacy-runtime-support) section, NTARH's App Router support starts at `14.0.4` since before then there was quite a bit of internal churn in the Next.js code base. I should probably add that caveat higher up in the README.

**Comment by kingstarfly** [comment]
Hey @Xunnamius, thanks for the clarification! 👍 

> As of version 4.0.0, NTARH supports both the App Router (for next@>=14.0.4) and the "legacy" Pages Router Next.js APIs.
> Additionally, as of version 2.1.0, NTARH is fully backwards compatible with Next.js going allll the way back to next@9.0.0 [when API routes were first introduced](https://nextjs.org/blog/next-9)!

Do you mean that there is no version of NTARH that will support usage of App Router if the Next.js version is below 14? 
Or do you mean that I need to use an older version of NTARH? 

If it's the latter, on the note of changing the README, you might want to consider having a table mapping of NTARH version and Next.js versions for App Router support.

Thanks once again! Keen to use NTARH in my project.

**Comment by Xunnamius** [comment]
> Do you mean that there is no version of NTARH that will support usage of App Router if the Next.js version is below 14?

Unfortunately, yes.


> As of version 4.0.0, NTARH supports both the App Router (for next@>=14.0.4) and the "legacy" Pages Router Next.js APIs.
> 
> Additionally, as of version 2.1.0, NTARH is fully backwards compatible with Next.js going allll the way back to next@9.0.0 when API routes were first introduced!

These statements are supposed to be orthogonal: the first describe Pages Router vs App Router support while the second talks about tracking the physical locations of Next.js internal functions/classes. I can see now how this could be confusing and I'll have to reword it :)

When NTARH 1 was released, it only supported the Pages Router for the latest version of Next.js at the time (likely Next.js version 10). With NTARH version 2.1.0, we [started supporting](https://github.com/Xunnamius/next-test-api-route-handler/tree/v2.1.0?tab=readme-ov-file#next-test-api-route-handler) the Pages Router for _all_ Next.js versions back to version 9, which is where that second statement comes from. This was significant because there were [various points of code churn](https://github.com/Xunnamius/next-test-api-route-handler/blob/1f81990959fd74bf9a8ac26822937fc237889201/test/integration-client-next.test.ts#L22-L31) between next@9 and next@12 where the Next.js developers physically moved the internal API resolver (the relatively-simple `apiResolver` function) to different locations, and NTARH <2.1 wasn't tracking that properly.

I tacked on that first statement when NTARH 4 was released earlier this year, which added support for the App Router by tracking a second internal API resolver (the `AppRouteRouteModule` class). At that point, Next.js was at version 14.0.4. I avoided implementing App Router support for next@13 since the App Router was undergoing extensive changes with much greater code churn (even at the minor release level) compared to the Pages Router during next@9-12. Unfortunately, it'd likely be quite a bit of work to support the various disparate evolutions of `AppRouteRouteModule` before things stabilized, so I planted the flag at Next.js version 14.0.4.

**Comment by Xunnamius** [comment]
I'll investigate this further just to make sure some bug hasn't snuck in and I'll close if there are no further developments. Thanks for the README suggestions.

**Comment by Lada496** [comment]
Hi @Xunnamius, I also got the same error and came across this thread. 
I'm using these environments:
next-test-api-route-handler: v4.0.8,
next: v14.2.1,
node: v20.14.0

As far as I understand, my versions are updated to work with next-test-api-route-handler. 
Would you come up with another reason why I got `ReferenceError: Request is not defined`? Thanks.

**Comment by Xunnamius** [comment]
Hmm. Are you using jest and jsdom? @Lada496

**Comment by Lada496** [comment]
@Xunnamius Thanks for your reply. Yes, here is my jest.config.js. Another thing I can come up with is I'm using TypeScript(5.4.2). 
```javascript
import type { Config } from 'jest'
import nextJest from 'next/jest.js'

const createJestConfig = nextJest({
  // Provide the path to your Next.js app to load next.config.js and .env files in your test environment
  dir: './',
})

// Add any custom config to be passed to Jest
/** @type {import('jest').Config} */
const config: Config = {
  coverageProvider: 'v8',
  testEnvironment: 'jsdom',
  // Add more setup options before each test is run
  // setupFilesAfterEnv: ['<rootDir>/jest.setup.ts'],
  moduleNameMapper: {
    // ...
    '^@/components/(.*)$': '<rootDir>/components/$1',
  },
  preset: 'ts-jest',
}

// createJestConfig is exported this way to ensure that next/jest can load the Next.js config which is async
export default createJestConfig(config)

```

**Comment by Xunnamius** [comment]
Unfortunately, jsdom does not support browser globals like fetch or text encoder. This is a known issue on their end. More about that [here](https://github.com/Xunnamius/next-test-api-route-handler?tab=readme-ov-file#jsdom-support) along with some workarounds.

**Comment by Lada496** [comment]
> @Lada496 Unfortunately, jsdom does not support browser globals like fetch or text encoder. This is a known issue on their end. More about that [here](https://github.com/Xunnamius/next-test-api-route-handler?tab=readme-ov-file#jsdom-support) along with some workarounds.

I got it. Thank you @Xunnamius for your support!
